### ISSUE TITLE
detect region for flag in /int/, /sp/, /pol, and /bant/bots using Telegram DC

### ISSUE THREAD

**Issue by aicynide** [Charibdys/Private-Parlor#100]
https://core.telegram.org/api/datacenter

Or let users set flag

**Comment by Charibdys** [comment]
A /sig command could be implemented but it would not be possible to use the datacenter API. The only location available through that API seems to be the datacenter's location, which would not be necessarily be indicative of the user's current location.

The /sig command would have to be ask the user to give a flag representing his location, which can then be stored in the database and attached to every message the user sends.

**Comment by aicynide** [comment]
https://github.com/raku-cat/secretlounge-ng/tree/flags

**Comment by Charibdys** [comment]
The flag setting feature has been implemented in [Private-Parlor-XT](https://github.com/Private-Parlor/Private-Parlor-XT/releases/tag/v1.1.0). I would recommend using that application to meet your need, as this repository is no longer maintained.
