### ISSUE TITLE
Allow editing of recent message

### ISSUE THREAD

**Issue by aicynide** [Charibdys/Private-Parlor#101]
https://github.com/dogmike/secretlounge-ng/blob/master/config.yaml.example#L20

**Comment by Charibdys** [comment]
This feature would be fraught with vulnerabilities and is not particuarly useful. By allowing editing, messages could be edited to replace inconspicuous text or media with obscene content.

This feature would also heavily conflict with the R9K auto moderator.

Messages can already be edited in PrivateParlor, but only by adding or removing a spoiler from a message's media.
