### ISSUE TITLE
[feature request] karma points for media like image,video,gif & stickers

### ISSUE THREAD

**Issue by aicynide** [Charibdys/Private-Parlor#103]

**Comment by Charibdys** [comment]
There's no particular reason for specific media to be worth different karma points. No other major application that implements a karma system does something like this. The karma system is easier to understand knowing that every upvote or downvote is worth a single point.

**Comment by aicynide** [comment]
@Charibdys i mean this thing https://github.com/dogmike/secretlounge-ng/blob/master/config.yaml.example#L34
Many users spam cringe stickers/gif -1 karma for them

**Comment by Charibdys** [comment]
In that case, making certain media cost karma in order to be sent could be a feature worth implementing. Some thought will be needed for how this could be integrated into the code in a configurable manner.

**Comment by Charibdys** [comment]
The karma points for media feature has been implemented in [Private-Parlor-XT](https://github.com/Private-Parlor/Private-Parlor-XT/releases/tag/v1.1.0). I would recommend using that application to meet your need, as this repository is no longer maintained.
