### ISSUE TITLE
motd announcement

### ISSUE THREAD

**Issue by aicynide** [Charibdys/Private-Parlor#105]
* **Is your feature request related to a problem? Please describe.**

* **What is the expected behavior of this feature?**
A clear and concise description of what you want the feature to do.

* **What is the motivation / use case for this feature?**

* **Other information** (e.g. detailed explanation, related issues, code examples)

**Comment by Charibdys** [comment]
Fill out the feature template, as it's difficult to tell what feature you want from two words in the title.

If this is supposed to be an announcement or redelivering of the MOTD/rules for when they are changed, then it could be implemented, but is it necessary? The MOTD/rules are changed rarely, and if they receive some major change then the host typically tells the chat.

**Comment by aicynide** [comment]
Separate rules and motd command please.
Users can view rules with /rules command & / motd command only for motds, everytime motd is set, its forwarded to all users

**Comment by Charibdys** [comment]
The /rules command is an alias of /motd. This is fine considering how the MOTD is used for showing rules of the chat. This is generally the purpose of an MOTD anyways; despite its name, it typically remains static over time.

If the host wants to make a literal message of the day that is relayed to all users, the /hostsay command or its equivalent can be used.

**Comment by aicynide** [comment]
`/hostsay` what? New to me! Didn't know it exists. 
Thank you

**Comment by Charibdys** [comment]
Ranks can be defined to have permission to use a `/ranksay` command. This allows the user to send an official system message signed with the name of the rank. 

For example, a mod can use either the `/ranksay` or `/modsay` command to send a message like "[message] **~~Mod**"

The *say commands use the name of the rank preceding it in the signature, so `/adminsay` gives "[message] **~~Admin**", and `/hostsay` gives "[message] **~~Host**".

Rank permissions and ranksay is explained in more detail here: https://github.com/Charibdys/Private-Parlor/wiki/Rank-Permissions
