### ISSUE TITLE
Inline image search

### ISSUE THREAD

**Issue by aicynide** [Charibdys/Private-Parlor#109]
* **Is your feature request related to a problem? Please describe.**
Nope
* **What is the expected behavior of this feature?**
A clear and concise description of what you want the feature to do.

Since this is a imageboard bot let users search images inline to send using yandex/whoogle/searx-ng api

* **What is the motivation / use case for this feature?**

Telegram  bot Inline feature

* **Other information** (e.g. detailed explanation, related issues, code examples)

   Besides images, allow searching youtube video search(optionally download using yt-dlp if possible, imdb link of movie, gifs

**Comment by Charibdys** [comment]
Won't implement, there are other inline bots for this use case (see @bing, @gif on Telegram).
This would also go beyond the scope of an anonymous message relay bot.
