### ISSUE TITLE
Reverse Image search

### ISSUE THREAD

**Issue by aicynide** [Charibdys/Private-Parlor#110]
**Is your feature request related to a problem? Please describe.**
Currently, Private-Parlor is missing a crucial feature – the ability to perform reverse image searches. This feature is important because it allows users to get the sauce of anime or lewd images

**What is the expected behavior of this feature?**
The reverse image search feature should allow users to upload an image, and the bot should perform a reverse image search on popular search engines (e.g., Yandex, TinEye,SauceNao,trace.moe). The bot should then provide results with links to the original sources or related pages where the image appears.

**What is the motivation / use case for this feature?**
- **Source Attribution:** Users can find the original source of images to give proper attribution.

**Other information**
This feature would greatly enhance the functionality and utility of private-parlor. It's particularly important for maintaining a safe and reliable imageboard environment. Implementing this feature would improve the overall user experience and contribute to the platform's credibility.

**Comment by Charibdys** [comment]
Won't implement. This goes beyond the scope of Private Parlor and there are already bots that solve this problem (see @reverseSearchBot on Telegram)

Private Parlor is not an imageboard. While it mimics some imageboard functionality, at the end of the day it is analogous to a group chat on Telegram where everyone's names and icons are invisible.
