### ISSUE TITLE
log in stdout

### ISSUE THREAD

**Issue by aicynide** [Charibdys/Private-Parlor#113]
* **Is your feature request related to a problem? Please describe.**

Its literally a feature request why should there any problem

* **What is the expected behavior of this feature?**
A clear and concise description of what you want the feature to do.

Hey if i enable log file location, stdout is blank, please enable it. 

* **What is the motivation / use case for this feature?**

mpv always print log in stdout even log file is specified 

* **Other information** (e.g. detailed explanation, related issues, code examples)

Its not compulsory right?

**Comment by Charibdys** [comment]
Implemented logging to STDOUT when a log file is configured in 9b0dffa
