### ISSUE TITLE
Is it possible to bridge the bot with lynxchan/jschan board or thread?

### ISSUE THREAD

**Issue by aicynide** [Charibdys/Private-Parlor#114]
* **Is your feature request related to a problem? Please describe.**

Yes, the problem its not possible to implement thread in telegram bot

* **What is the expected behavior of this feature?**
A clear and concise description of what you want the feature to do.

Let users browse the imageboard from both telegram bot & web/android/ios app supporting lynxchan and cross-post from telegram or web according to user's wish

* **What is the motivation / use case for this feature?**

I had previously requested for a web-ui for Private-Parlor for managing the bot from web-ui easily than hard-to-use linux cli

* **Other information** (e.g. detailed explanation, related issues, code examples)

If you think bridging to lynxchan will make this repo bloated, lets develop a  third-party plugin to bridge

**Comment by Charibdys** [comment]
It could be possible, but what you're describing is a different application. Private Parlor is a Telegram bot for making anonymous group chats. It is not an imageboard, so it does not need threads. Private Parlor is more akin to an anonymous group chat where the names and profile pictures are not visible, or an IRC. Both group chats and IRC's rarely have threads.

PrivateParlor already meets the goal of establishing anonymous chats on Telegram; there is no need for Private Parlor to crosspost to an imageboard, or for imageboards to crosspost to the bot. This would make it complicated to use the bot for the average user. If a user wants to use an imageboard, he can use a browser or an imageboard viewing app like [Kuroba](https://github.com/K1rakishou/Kuroba-Experimental). 

There may be merit in a separate Telegram bot that acts as a feed for certain imageboards, but this is not something I want to work on right now, nor is it something that will be implemented in Private Parlor.

It is possible to make using Linux easier by installing VNC and a desktop environment like XFCE or LXDE to your server and connecting to it using a remote desktop client. You can then manage scheduled tasks and the database using some graphical tools.

**Comment by aicynide** [comment]
We could view and reply in lynxchan boards without leaving telegram

**Comment by Charibdys** [comment]
A bot with that capability could be possible, but I do not see this being at all very useful, and that capability will not be implemented in Private Parlor.
