### ISSUE TITLE
message translation for /int/ bot

### ISSUE THREAD

**Issue by aicynide** [Charibdys/Private-Parlor#115]
* **Is your feature request related to a problem? Please describe.**

* **What is the expected behavior of this feature?**
A clear and concise description of what you want the feature to do.

Translate user message using google translate/yandex api. I guess instead of add this feature in main repo, a separate third-party plugin should ne developed

* **What is the motivation / use case for this feature?**
 Potential of plugin system.

* **Other information** (e.g. detailed explanation, related issues, code examples)

**Comment by Charibdys** [comment]
Message translation has already been implemented in the [official Telegram desktop and mobile clients](https://telegram.org/blog/reactions-spoilers-translations#message-translation). It works for messages sent by bots too.
