### ISSUE TITLE
stripping email & phone_number not working

### ISSUE THREAD

**Issue by aicynide** [Charibdys/Private-Parlor#96]
Please share linked_network.yaml

**Comment by Charibdys** [comment]
Email and phone number MessageEntity stripping was resolved in the dev channel: https://t.me/privateparlor/55?single
In short, the bot does strip these MessageEntities, however, some Telegram clients see the email or phonenumber in the message text and render it as a clickable link anyways. For instance, mobile Telegram clients often render phone numbers as clickable "tel:" links, whereas desktop clients will not.

The linked_network key in the config file is meant to be personalizable. Chats that someone else links to may not be chats that you want to link to.
You can use various anonymous chat bot indexers to make your own linked_network.yaml file:

- https://secretlounge.net/list/
- https://t.me/catloungeadmin/41

These are two separate issues. Please create issues for one thing and one thing only.
